name: drive
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# version: 1.0.0+1
version: 1.0.6+42

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.1
  cached_network_image: ^3.2.0
  charts_flutter: ^0.12.0
  collection: ^1.15.0
  connectivity: ^3.0.6
  contacts_service: ^0.6.3
  cron: ^0.4.0
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  dots_indicator: ^2.0.0
  firebase_core: ^1.10.0
  firebase_dynamic_links: ^2.0.9
  firebase_messaging: ^11.2.11
  flutter:
    sdk: flutter
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  flutter_facebook_auth: ^4.0.0
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_radar_chart: ^0.2.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  flutter_xlider:
    git:
      url: https://github.com/rutvikgumasana/flutter_xlider
  font_awesome_flutter: ^9.1.0
  geolocator: ^8.0.3
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.1
  google_mobile_ads: ^1.0.1
  google_sign_in: ^5.2.1
  google_sign_in_web: ^0.10.0+3
  http: ^0.13.3
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+11
  in_app_purchase: any
  intl: ^0.17.0
  keyboard_dismisser: ^2.0.0
  launch_review: ^3.0.1
  line_chart: ^1.1.11
  path_provider: ^2.0.8
  percent_indicator: ^4.0.0
  permission_handler: ^8.3.0
  pie_chart: ^5.1.0
  pin_code_fields: ^7.3.0
  qr_flutter: ^4.0.0
  rxdart: ^0.26.0
  scroll_snap_list: ^0.8.4
  scrollable_positioned_list: ^0.2.3
  share: ^2.0.4
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  store_redirect: ^2.0.1
  sqflite: ^2.0.1
  syncfusion_flutter_gauges: ^19.2.60
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.18
  video_player: ^2.2.8
  in_app_review: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/default/
    - assets/images/flag/
    - assets/icons/
    - assets/icons/svg_icons/
    - assets/json/
    - assets/gif/
    - assets/fonts/
    - assets/database/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/Cera_Pro-Black.otf
          weight: 800
        - asset: assets/fonts/Cera_Pro-Bold.otf
          weight: 700
        - asset: assets/fonts/Cera_Pro-Medium.otf
          weight: 600
        - asset: assets/fonts/Cera_Pro-Regular.otf
          weight: 500
        - asset: assets/fonts/Cera_Pro-Light.otf
          weight: 400
        - asset: assets/fonts/Cera_Pro-Thin.otf
          weight: 300
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
